### ISSUE TITLE
Update to webgl2?

### ISSUE THREAD

**Issue by ibgreen** [vorg/webgl-debug#1]
https://github.com/KhronosGroup/WebGLDeveloperTools has been updated to support WebGL2, which is great, but I just realized that the corresponding npm module is independent and published from this repo instead.

Any chance we could get an update published on npm? If it helps, I could try putting together a PR, let me know.

FWIW, we have been using this module for debugging with great success, but it doesn't cover WebGL2 functionality which we are increasingly relying on.

**Comment by ibgreen** [comment]
@vorg 

Due to lack of response I assume this is repository is no longer maintained.

I'm considering forking the repo and publishing as a separate npm module.

Or if you prefer, you could add me to your repo/npm module and I could take over the maintenance.

**Comment by vorg** [comment]
Hi, i just saw you issue. Let me have a look and try updating it tomorrow.

**Comment by vorg** [comment]
This has beed fixed in https://github.com/vorg/webgl-debug/commit/f2d0fb7cb0207d35260c521a735892d243fa8387 and verified using this example https://github.com/vorg/webgl-debug/blob/master/example/index.js
